version: "3.8"

services:
  jupyterhub:
    image: mnc_jupyter:latest
    environment:
      notebook_dir: /workspace
    ports:
      - 9010:8000
    volumes:
      - /DATA:/workspace
      - ./:/vol_hub_setting/
    shm_size: 32G
    ulimits:
        core:
            hard: 0
            soft: 0
    
  mariadb:
    image: mariadb:10
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - /DATA/mariadb/data:/var/lib/mysql
      - /DATA/mariadb/sock:/run/mysqld
    profiles:
      - with-db

# docker-compose up (without mariadb)
# docker-compose --profile with-db up (with mariadb)
